fix(Dados Cadastrais): ORB-1193 - Adição de restrição e mudança de formato para o campo PartiesParticipation.documentCountry
Sensedia/areadesenvolvedor pull request #520
Opened 2022-03-11 18:39 UTC by Lucas-Silva75

2022-03-11 19:28 UTC, rmGinner requested changes

2022-03-11 20:45 UTC, Lucas-Silva75 commented on documentation/source/swagger/parts/schemas/customers_apis/PartiesParticipation.yaml
> +    pattern: '[\w*\W*]'
boa Rodrigo, acho super válido!

2022-03-14 13:09 UTC, cleiltonoliveira approved these changes

2022-03-14 16:50 UTC, rmGinner approved these changes

2022-03-14 16:51 UTC, merged